name: 'github-discord'
description: 'Github Discord Webhook Handler'
author: 'Noctonyx'
inputs:
  webhook:
    required: true
  title:
    required: true
    description: 'Message Title'
    default: 'Message Title'
  text:
    required: true
  color:
    required: true
    description: 'Message Color'
    default: '#00b0f4'
  project:
    required: false
    default: ${{github.repository}}
  branch:
    required: false
    default: ${{github.ref}}
  workflow:
    required: false
    default: ${{github.workflow}}
runs:
  using: 'node12'
  main: 'dist/index.js'
